# This code was mostly generated by Github Copilot

import random

def generate_maze(width, height):
    maze = [[1 for _ in range(width)] for _ in range(height)]
    
    def carve(x, y):
        dirs = [(0,1), (1,0), (0,-1), (-1,0)]
        random.shuffle(dirs)
        for dx, dy in dirs:
            nx, ny = x + dx*2, y + dy*2
            if 0 <= nx < width and 0 <= ny < height and maze[ny][nx] == 1:
                maze[y + dy][x + dx] = 0
                maze[ny][nx] = 0
                carve(nx, ny)
                
    # Start at (1,1)
    maze[1][1] = 0
    carve(1, 1)
    return maze

def print_maze(maze):
    for row in maze:
        print(''.join(['🟦' if cell else '  ' for cell in row]))

if __name__ == '__main__':
    width, height = 21, 21  # Must be odd numbers
    maze = generate_maze(width, height)
    print_maze(maze)